- name: Setting up the 3-nodes ha cluster
  hosts: hanodes_public
  gather_facts: false
  become: true
  vars_files:
    - credentials.yml
  vars:
    apache_config_file: "/etc/httpd/conf/httpd.conf"  # Change this to "/etc/apache2/ports.conf" for Debian-based systems
    virtual_ip: "192.168.1.100"  # Replace this with the desired virtual IP

  tasks:
    - name: Enable the HighAvailability Repo
      command: "yum-config-manager --enable HighAvailability"

    - name: Install the Packages
      yum:
        name:
          - httpd
          - pacemaker
          - pcs
          - iscsi-initiator-utils
          - firewalld
        state: present

    - name: Start the pcs service
      service:
        name: "pcsd"
        state: started
        enabled: true

    - name: Enable cluster on both nodes
      command: pcs cluster setup --force --name mycluster {{ groups['hanodes_public'] | join(' ') }}
      when: inventory_hostname == groups['hanodes_public'][0]

    - name: Set the password for the use hacluster
      user:
        name: "{{ username }}"
        password: "{{ password  | password_hash('sha512') }}"
        update_password: always

    - name: Authenticate the cluster
      command: "pcs cluster auth {{ groups['hanodes_public'][0] }} {{ groups['hanodes_public'][1] }} -u {{ username }} -p {{ password }}"
      register: auth_status
      run_once: true
      delegate_to: '{{ groups.hanodes_public[0] }}'
      

    - name: Print the authorization status
      debug:
        msg: "{{ auth_status }}"
      run_once: true

    - name: Gather cluster status
      command: "pcs cluster status"
      register: cluster_status
      ignore_errors: true
    
    - name: Setup the HA-Cluster
      command: "pcs cluster setup --name --force {{ groups['hanodes_public'][0] }} {{ groups['hanodes_public'][1] }}"
      register: setup_status
      #when: inventory_hostname == hanodes[0]
      run_once: true
      delegate_to: "{{ groups['hanodes_public'][0] }}"
      when: cluster_status.rc | int != 0

    - name: Print the cluster setup output
      debug:
        msg: "{{ setup_status }}"
      run_once: true


    - name: Rename File
      command: "cd /etc/corosync && sudo mv corosync.conf.example corosync.conf"
      register: start_status
      #when: inventory_hostname == hanodes[0]
      run_once: true
      delegate_to: "{{ groups['hanodes_public'][1] }}"
      when: cluster_status.rc | int != 0



    - name: Start the HA-Cluster
      command: "pcs cluster start --all"
      register: start_status
      #when: inventory_hostname == hanodes[0]
      run_once: true
      delegate_to: "{{ groups['hanodes_public'][0] }}"
      when: cluster_status.rc | int != 0

    - name: Print the cluster start output
      debug:
        msg: "{{ start_status }}"
      run_once: true

    - name: Enable the HA-Cluster
      command: "pcs cluster enable --all"
      register: enable_status
      #when: inventory_hostname == hanodes[0]
      run_once: true
      delegate_to: "{{ groups['hanodes_public'][0] }}"
      when: cluster_status.rc | int != 0

    - name: Print the cluster enable output
      debug:
        msg: "{{ enable_status }}"
      run_once: true

    - name: Gather cluster status
      command: "pcs cluster status"
      register: status

    - name: Check and print the cluster Status
      debug:
        msg: "{{ status }}"
      run_once: true
    
    - name: Configure Apache to listen on the virtual IP
      lineinfile:
        path: "{{ apache_config_file }}"
        line: "Listen {{ virtual_ip }}:80"
      when: apache_config_file is defined

    - name: Create Apache as a cluster resource
      command: >
        pcs resource create apache ocf:heartbeat:apache
        configfile="{{ apache_config_file }}"
        statusurl="http://{{ virtual_ip }}/server-status"
        op monitor interval=30s

    - name: Enable Apache resource
      command: "pcs resource enable apache"

    - name: Allow HTTP traffic through the firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes