- name: Configure iSCSI initiator for node 1
  hosts: hanodes_public
  become: true
  vars: 
    - initiator_name: iqn.2023-03.online.durgesh:nodes
    - target_iqn: iqn.2023-03.online.durgesh:target
    - target: 3.129.128.94
    - private_target: 172.31.17.16
  tasks: 
    - name: Install iSCSI initiator utilities
      package:
        name: iscsi-initiator-utils
        state: present 
    
    - name: Check if initiator file exists
      stat:
        path: /etc/iscsi/initiatorname.iscsi
      register: initiatorname_file

    - name: Create initiatorname.iscsi file if it does not exist
      copy:
        content: "InitiatorName={{ initiator_name }}"
        dest: /etc/iscsi/initiatorname.iscsi
      when: not initiatorname_file.stat.exists
    
    - name: Configure name
      lineinfile:
        path: /etc/iscsi/initiatorname.iscsi
        line: "InitiatorName={{ initiator_name }}"
    
    - name: Discover iSCSI trget
      shell: "iscsiadm -m discovery -t st -p {{ target }}"

    - name: Log in to iSCSI target
      shell: "iscsiadm -m node -T {{ target_iqn }} -p {{ private_target }} -l"

    - name: Create the mount point directory
      file:
        path: /mount
        state: directory

    - name: Get the file system UUID
      shell: blkid -o value -s UUID /dev/sda
      register: uuid

    - name: Add entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "UUID={{ uuid.stdout }} /mount ext3 defaults,_netdev 0 0"
        state: present
    - name: Log out to iSCSI target
      shell: "iscsiadm -m node -T {{ target_iqn }} -p {{ private_target }} --logout"